### ISSUE TITLE
自定义中间按钮导致底部tabbar消失

### ISSUE THREAD

**Issue by lazycoder417** [xiezhongmin/XZMTabbarExtension#4]
你好，很感谢你的代码，最近在使用这个代码的时候，发现在ios10的系统上设置中间按钮会让底部tabbar消失不见，而且中间按钮位置会偏移，且点击不了。在10以下的系统没有这个问题。
- (instancetype)initWithFrame:(CGRect)frame
  {
  if (self = [super initWithFrame:frame]) {
      UIButton  *centerButton = objc_getAssociatedObject(self, &AssociatedButtonKey);
      if (!centerButton) {
          centerButton = [UIButton buttonWithType:UIButtonTypeCustom];
          objc_setAssociatedObject(self, &AssociatedButtonKey, centerButton, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
      }
      [self addSubview:centerButton];
  }
  return self;
  }

这事那段代码 注视之后，底部的tabbar就出现了。想请问 这个应该怎么解决 万分感谢！

**Comment by XXVVWWEEIIBBOO** [comment]
我也遇到这个问题了.

**Comment by xiezhongmin** [comment]
感谢支持，已修复，请更新代码
